### ISSUE TITLE
菜单类型怎么没有`media_id`

### ISSUE THREAD

**Issue by oimken** [largezhou/wechat-menu#11]
菜单类型这里没有找到 `media_id` 的选项，这个应该很放方便地直接回复素材的方式啊， 请问有没有机会加上呢？
```
[
    'type'     => 'media_id',
    'name'     => '今日新闻',
    'media_id' => 'n5kf351WGJ2nRnzGdrXLWisPtEmM4PwCrnXI',
 ],
```

**Comment by largezhou** [comment]
太忙了，，，都没看到这消息，，，有空看一下，，，

**Comment by largezhou** [comment]
简单添加了下 `media_id` 和 `view_limited` 菜单类型，，，可以查看

http://wechat-menu.largezhou.cn/
